// <auto-generated />
using System;
using CouncilAtelier.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouncilAtelier.Migrations
{
    [DbContext(typeof(CouncilAtelierContext))]
    [Migration("20260120154718_AddOgrenciTables")]
    partial class AddOgrenciTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CouncilAtelier.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bazin’e göre plastik sanatların kökeninde insanın ölüme karşı koyma ve zamanı durdurma arzusu vardır (\"Mumya Kompleksi\"). Resim ne kadar gerçekçi olursa olsun sanatçının öznel yorumundan geçer. Fotoğraf ise insan müdahalesi olmadan, ışık ve kimyasal süreçle görüntü üretir; bu yüzden “nesnellik” iddiası taşır. Bu durum fotoğrafın ontolojik statüsünü değiştirir: Fotoğraf bir taklit değil, nesnenin varlığından kopup gelen bir uzantı gibi işler (parmak izi, gölge benzeri). Sinema ise bu gücü ileri taşır: Donmuş görüntüyü zamanın içine yerleştirerek gerçekliğin değişim içindeki nesnelliğini sunar.",
                            IsDeleted = false,
                            PublishedAt = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "fotografik-goruntunun-ontolojisi",
                            Summary = "André Bazin, insanın zamanı durdurma arzusunu “Mumya Kompleksi” olarak ele alır; fotoğrafın mekanik süreçle nesnelliği dondurduğunu, sinemanın ise bu nesnelliği zamanın akışına taşıdığını savunur.",
                            Title = "Fotoğrafik Görüntünün Ontolojisi"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Benjamin’e göre modern teknik çoğaltım, sanat yapıtının benzersiz “şimdi ve burada”lığını zayıflatır; bu benzersiz varlık hâline “aura” denir. Çoğaltım, eseri geleneğin alanından çıkarır; nesneye “yakınlaşma” arzusu mesafeye dayalı aurayı çözer. Bu dönüşümle sanat, ritüel/tapınma değerinden sergileme değerine kayar; fotoğraf ve sinema yeni bir algı rejimi üretir. Sinemada oyuncu kameraya oynar; yıldız sistemi yapay bir aura kurar. Kurgu şok etkisiyle algıyı dönüştürür; kamera “optik bilinçdışı”nı görünür kılar. Sonuçta sanat siyasete eklemlenir; Benjamin faşizmin siyaseti estetize etmesine karşı sanatın siyasallaştırılmasını savunur.",
                            IsDeleted = false,
                            PublishedAt = new DateTime(1936, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "teknigin-olanaklariyla-cogaltildigi-cagda-sanat-yapiti",
                            Summary = "Walter Benjamin, teknik çoğaltımın (fotoğraf/sinema) sanat yapıtının “aura”sını aşındırdığını, sanatın ritüel temelden kopup sergileme ve siyasete eklemlendiğini tartışır.",
                            Title = "Tekniğin Olanaklarıyla Çoğaltılabildiği Çağda Sanat Yapıtı"
                        });
                });

            modelBuilder.Entity("CouncilAtelier.Models.Basvuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SelectedItem")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("CouncilAtelier.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sinema"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fotoğraf"
                        });
                });

            modelBuilder.Entity("CouncilAtelier.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("CouncilAtelier.Models.OgrenciProgramKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("ProgramId");

                    b.ToTable("OgrenciProgramKayitlari");
                });

            modelBuilder.Entity("CouncilAtelier.Models.OgrenciWorkshopKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("OgrenciWorkshopKayitlari");
                });

            modelBuilder.Entity("CouncilAtelier.Models.Programlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Programlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Şehri bir gözlemci gibi okumayı ve karar anını yakalamayı hedefleyen atölye. Sokakta insanla iletişim, görünmez olma teknikleri, ışık-gölge kullanımı ve hikaye bütünlüğü. 1 gün teori + 1 gün saha çekimi.",
                            IsDeleted = false,
                            Title = "Sokağın Hafızası: Belgesel ve Sokak Fotoğrafçılığı"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Teknikten çok gözü eğitmeyi hedefleyen program. Altın oran, denge, negatif alan, renk teorisi ve izleyicinin gözünü kare içinde yönlendirme.",
                            IsDeleted = false,
                            Title = "Bakışın Ritmi: Kompozisyon ve Görsel Estetik"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "RAW dosyadan kişisel stile uzanan süreç. Lightroom ve Photoshop temelleri, color grading, lokal müdahaleler ve preset oluşturma. Laptop zorunludur.",
                            IsDeleted = false,
                            Title = "Dijital Karanlık Oda: RAW İşleme ve Stil Geliştirme"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Bir fikrin sinema diline dönüşümü. 3 perde yapısı, karakter arkı, diyalog yazımı ve senaryo formatı (Celtx / Final Draft). 4 haftalık program.",
                            IsDeleted = false,
                            Title = "Kâğıttan Perdeye: Senaryo ve Karakter Tasarımı"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Kurgu teorisi, ritim, duygu inşası ve görüntü-ses ilişkisi. Kuleshov etkisi ve Adobe Premiere / DaVinci Resolve ile uygulamalar.",
                            IsDeleted = false,
                            Title = "Kurgu Masasında Hikaye: Montajın Görünmez Gücü"
                        });
                });

            modelBuilder.Entity("CouncilAtelier.Models.Workshoplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Workshoplar");
                });

            modelBuilder.Entity("CouncilAtelier.Models.OgrenciProgramKayit", b =>
                {
                    b.HasOne("CouncilAtelier.Models.Ogrenci", "Ogrenci")
                        .WithMany("ProgramKayitlari")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAtelier.Models.Programlar", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("CouncilAtelier.Models.OgrenciWorkshopKayit", b =>
                {
                    b.HasOne("CouncilAtelier.Models.Ogrenci", "Ogrenci")
                        .WithMany("WorkshopKayitlari")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAtelier.Models.Workshoplar", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CouncilAtelier.Models.Programlar", b =>
                {
                    b.HasOne("CouncilAtelier.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CouncilAtelier.Models.Workshoplar", b =>
                {
                    b.HasOne("CouncilAtelier.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CouncilAtelier.Models.Ogrenci", b =>
                {
                    b.Navigation("ProgramKayitlari");

                    b.Navigation("WorkshopKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
