// <auto-generated />
using CouncilAtelier.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouncilAtelier.Migrations
{
    [DbContext(typeof(CouncilAtelierContext))]
    [Migration("20260106113632_SeedCouncilContent")]
    partial class SeedCouncilContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CouncilAtelier.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sinema"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fotoğraf"
                        });
                });

            modelBuilder.Entity("CouncilAtelier.Models.Programlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Programlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Şehri bir gözlemci gibi okumayı ve karar anını yakalamayı hedefleyen atölye. Sokakta insanla iletişim, görünmez olma teknikleri, ışık-gölge kullanımı ve hikaye bütünlüğü. 1 gün teori + 1 gün saha çekimi.",
                            Title = "Sokağın Hafızası: Belgesel ve Sokak Fotoğrafçılığı"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Teknikten çok gözü eğitmeyi hedefleyen program. Altın oran, denge, negatif alan, renk teorisi ve izleyicinin gözünü kare içinde yönlendirme.",
                            Title = "Bakışın Ritmi: Kompozisyon ve Görsel Estetik"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "RAW dosyadan kişisel stile uzanan süreç. Lightroom ve Photoshop temelleri, color grading, lokal müdahaleler ve preset oluşturma. Laptop zorunludur.",
                            Title = "Dijital Karanlık Oda: RAW İşleme ve Stil Geliştirme"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Bir fikrin sinema diline dönüşümü. 3 perde yapısı, karakter arkı, diyalog yazımı ve senaryo formatı (Celtx / Final Draft). 4 haftalık program.",
                            Title = "Kâğıttan Perdeye: Senaryo ve Karakter Tasarımı"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Kurgu teorisi, ritim, duygu inşası ve görüntü-ses ilişkisi. Kuleshov etkisi ve Adobe Premiere / DaVinci Resolve ile uygulamalar.",
                            Title = "Kurgu Masasında Hikaye: Montajın Görünmez Gücü"
                        });
                });

            modelBuilder.Entity("CouncilAtelier.Models.Programlar", b =>
                {
                    b.HasOne("CouncilAtelier.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
